[behave.formatters]
allure = allure_behave.formatter:AllureFormatter

[behave.userdata]
image_source = registry
image_url = docker://kubevirt/cirros-container-disk-demo:latest
image_size = 20Gi
sc_fstype = ext4
sc_mode = Thin
sc_provisioner = kubesan.gitlab.io
sc_vg = kubesan-vg
access_modes = ReadWriteMany
volume_mode = Block
vm_username = kubesan
vm_password = redhat

[report_portal]
# api_key =
client_type = SYNC
# endpoint =
launch_attributes = KubeSAN OpenShift Kubernetes Storage
launch_description = KubeSAN Testing Tool
launch_name = ksantt
is_skipped_an_issue = False
log_layout = Nested
# project =
