[behave.formatters]
allure = allure_behave.formatter:AllureFormatter

[behave.userdata]
image_url = https://github.com/cirros-dev/cirros/releases/download/0.6.3/cirros-0.6.3-x86_64-disk.img
sc_fstype = ext4
sc_mode = Thin
sc_provisioner = kubesan.gitlab.io
sc_vg = kubesan-vg

[report_portal]
# api_key =
client_type = SYNC
# endpoint =
launch_attributes = KubeSAN OpenShift Kubernetes Storage
launch_description = KubeSAN Testing Tool
launch_name = ksantt
is_skipped_an_issue = False
log_layout = Nested
# project =
